import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'djzhang' at '10/13/14 11:06 AM' with Gradle 1.12
 *
 * @author djzhang, @date 10/13/14 11:06 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

    }
}
